# Generated by Django 4.2.7 on 2024-02-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(blank=True, default=0, editable=False, null=True, verbose_name='Цена'),
        ),
    ]
